### ISSUE TITLE
Order in LogViewer is confusing

### ISSUE THREAD

**Issue by jenshp** [moqui/moqui-elasticsearch#11]
When looking at the log entries within a single page, they are ordered so that the most recent entry is at the bottom and the oldest at the top, so you see a timestamp-wise increasing order when scrolling down. However, when changing to the next page you see all entries older than the oldest of the previous page, so you see a timestamp-wise decreasing order.
While both orderings make sense when considered in isolation, one would expect the order to be consistent, either increasing or decreasing and the result is confusing.
This is a feature, as the reversing of the order is done explicitly and described in a comment, but maybe we should add an option to change this behavior?

**Comment by jonesde** [comment]
What would be better? Seeing the log messages in reverse order? Showing oldest first and requiring the user go to the last page to see the most recent (which is usually what you'll do with this)? In my initial tests with this it was really difficult to read through log messages when they are in reverse order... like REALLY bad. IMO it isn't that big a stretch to get used to subsequent pages having older log entries but each page displayed oldest to newest.

Unless someone wants to implement some sort of show most recent log messages along with a progressively loaded (paginated) scroll up then I don't see how this can easily be improved.

If you have a solution in mind that is usable we can leave this open, otherwise I'll close it and mark it 'wontfix'.

**Comment by jenshp** [comment]
My personal preference would be to have newest first and reloading the page as needed to see newer log entries. But it does not take that much effort to get used to the way it is now so it would not be high on my priority list.
