### ISSUE TITLE
How to enable `painless` script?

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-elasticsearch#13]
@jonesde,

I try to use painless script but it reports `script_lang not supported [painless]`, then notice the comments in https://github.com/moqui/moqui-elasticsearch/blob/master/build.gradle#L59-L64 which says `lang-painless` can't come from jcenter, but it seems it is avaible in jcenter now https://jcenter.bintray.com/org/codelibs/elasticsearch/module/lang-painless/5.4.1
```
compile group: 'org.codelibs.elasticsearch.module', name: 'lang-painless', version: '5.4.1'
```

I added `lang-painless`, `antlr4`,`asm-all` in the dependency 
```
compile group: 'org.antlr', name: 'antlr4', version: '4.5.3'
compile group: 'org.ow2.asm', name: 'asm-all', version: '5.1'
compile group: 'org.codelibs.elasticsearch.module', name: 'lang-painless', version: '5.4.1'
```
but still can't get painless script running due to elasticsearch still reporting `script_lang not supported [painless]`. I know this is more elasticsearch related configuration. I appreciate If you shed a light on this.

Meanwhile since `lang-painless` jar can get from jcenter, can it be enabled by default in this repo?

**Comment by jonesde** [comment]
As mentioned in the other/newer comments in the build.gradle file the real issue now is a classpath one, and it's not a simple issue. Other libraries use ASM and to avoid multiple versions on the classpath it needs to be shared, so far that is generally handled by adding it to the framework libs.

For any of these ElasticSearch modules to work the module configuration files also need to be in the home/modules directory like the current lang-groovy, reindex, and transport-netty4 modules.

Over time it has become more and more difficult to keep ElasticSearch running embedded, though it is extremely convenient. Module configurations like this are barely the surface of the mess it all is, classpath issues are bigger and we have to play some games on init as well in the ElasticSearchToolFactory. All of this has taken a lot of time over the years, especially since Elastic doesn't support this way of running it, and in 5.0.0 they even made some changes to try to prevent people from running this way... some of that they have backed off on as they now seem to have a priority to support at least test environments where this is done (most likely some customer of theirs pushing for that, one of the bigger influences on open source projects in general).

The day may come when we have to run it completely externally. You can do that now with configuration using different settings in the elasticsearch.yml file, though I haven't tried that for a long time so not sure what sorts of quirks or issues might come up. Running it externally you can easily have all the modules in place, or even use their commercial package with more security and management tools and such.

**Comment by shendepu** [comment]
Thanks David, I will use the external elasticsearch server, and configure moqui-elasticsearch as the native node client to the elasticsearch server. 

elasticsearch also had some statment that they prefer and may only support Http client in the future. I am not sure how long the java api of elasticsearch is still available. For now, I can use the java api to make very complex search and aggreggations

**Comment by jonesde** [comment]
For a long time I've been considering changing everything to run through the HTTP interface, but it requires a fair amount of new code to build the JSON for indexing, queries, etc instead of using the Java API. Sooner or later it may be necessary in order to support the newest versions of ElasticSearch. This would also have the benefit of not requiring any client libraries, so it might as well go back into the core framework (and then perhaps the moqui-elasticsearch component would only be for running an embedded version of ElasticSearch, or even starting up an external instance in another JVM but starting and stopping it automatically).

This will require a fair amount of effort so I haven't even touched it, but sooner or later might be worth doing and would be more flexible.

**Comment by shendepu** [comment]
Thanks for this information. I think this issue can be closed now.
