### ISSUE TITLE
Fail to search with inline groovy script after upgrade to elasticsearch 5.5.2

### ISSUE THREAD

**Issue by shendepu** [moqui/moqui-elasticsearch#17]
After commit 99705bd85a385492fcaeac7eac5d0635e2b0c070 upgrade 5.5.2 and latest 5.6.2, the search with inline groovy script fail with error 
```
script_score: the script could not be loaded
scripts of type [inline], operation [search] and lang [groovy] are disabled
```

But after adding 
```
script.engine.groovy.inline.search: on
```
in the elasticsearch.yml, it works. I guess it might be similar for `aggs`, `ingest`, `update`. 

I think it is a bug of elasticsearch since  https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html says this is depreciated, and `script.allowed_types` and `script.allowed_contexts` should be used, and by default all are allowed. 

This might be a walkaround for now before elasticsearch get it right.

**Comment by jonesde** [comment]
Yes, this is annoying. After the 5.5.2 update I tried various things in script.allowed_types and script.allowed_contexts and nothing worked, seems broken. While there have been a few good improvements in ElasticSearch over the last couple years most changes, especially deprecated and removed functionality and serious external layer changes have been awful. I don't know if Elastic.co had some engineering leadership changes or what, but the people at the helm now do nothing but make life difficult. I've seen them back off on a few things because their large paying customers demanded it, but in so many ways just more and more incompetence and making past use cases impossible... with more to come if their announcements are to be believed.

Rant over, I'll try this out.

**Comment by jonesde** [comment]
I just realized I don't have a good test case for this any more... the mantle-usl services that used to use inline groovy scripts for a simple multiplication in an aggregation now use pre-calculation with the newer feature in DataDocumentField to support inline groovy expressions.

Could you try it with the 2 lines currently commented using their new style of script configured, ie:

script.allowed_types: inline
script.allowed_contexts: search, aggs

With the old one there is a deprecation warning on startup, not a huge issue but would be nice to future proof this a bit better.

**Comment by shendepu** [comment]
I try it, but still fails. then I trying add `script.engine.groovy.inline.search: on`, then it works. 
I don't have use cases running inline groovy on `aggs`, `ingest` and `update` now, but I guess they would be same.

**Comment by jonesde** [comment]
Okay, I added the old style as well as the new to elasticsearch.yml and at least it starts up (in 5.5.2 it wouldn't even start with the new style ones uncommented). I'll leave it that way for now... see what Elastic.co has in store for us in upcoming releases!
